name: Build

on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: brew install cmake
    - name: Build
      run: |
        cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
        cmake --build build
    - uses: actions/upload-artifact@v4
      with:
        name: inferno_fs_patcher
        path: build/inferno_fs_patcher
